'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyTitle("DNNStuff.Aggregator"),  _
 Assembly: AssemblyDescription("DNNStuff.Aggregator - DNN7 Install - .NET 3.5"),  _
 Assembly: AssemblyCompany("DNNStuff"),  _
 Assembly: AssemblyProduct("DNNStuff Aggregator"),  _
 Assembly: AssemblyCopyright("Copyright (c) DNNStuff 2004-2012"),  _
 Assembly: ComVisible(false),  _
 Assembly: CLSCompliant(true),  _
 Assembly: AssemblyVersion("06.05.00"),  _
 Assembly: AssemblyFileVersion("06.05.00")> 

