'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: System.Reflection.AssemblyTitle("DNNStuff.Aggregator"),  _
 Assembly: System.Reflection.AssemblyDescription("DNNStuff.Aggregator - DNN7 Install"),  _
 Assembly: System.Reflection.AssemblyCompany("DNNStuff"),  _
 Assembly: System.Reflection.AssemblyProduct("DNNStuff Aggregator"),  _
 Assembly: System.Reflection.AssemblyCopyright("Copyright (c) DNNStuff 2017"),  _
 Assembly: System.Runtime.InteropServices.ComVisible(false),  _
 Assembly: System.CLSCompliant(true),  _
 Assembly: System.Reflection.AssemblyVersion("01.01.01"),  _
 Assembly: System.Reflection.AssemblyFileVersion("01.01.01")> 

