'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.Aggregator

    Partial Public Class EditModule

        '''<summary>
        '''lblTabModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTabModule As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboTabModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboTabModule As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkShowAllModules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowAllModules As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblShowAllModules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShowAllModules As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblInsertBreak control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInsertBreak As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkInsertBreak control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkInsertBreak As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTab As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboTab As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblLocale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLocale As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboLocale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboLocale As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblLoadEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLoadEvent As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboLoadEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboLoadEvent As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
