'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.Aggregator

    Partial Public Class ManageSkin

        '''<summary>
        '''lblEditTabSkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEditTabSkin As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboEditTabSkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboEditTabSkin As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblEditTabTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEditTabTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboEditTabTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboEditTabTemplate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblEditTabFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEditTabFile As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboEditTabFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboEditTabFile As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblSkinText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSkinText As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSkinText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSkinText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdSaveFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSaveFile As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''phEditSkinResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phEditSkinResults As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''lblTabSkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTabSkin As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboTabSkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboTabSkin As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblTabTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTabTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboTabTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboTabTemplate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblNewSkinName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNewSkinName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtNewSkinName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNewSkinName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''vldNewSkinName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldNewSkinName As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''vldNewSkinNameRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldNewSkinNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblOverwrite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOverwrite As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkOverwrite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkOverwrite As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdCopySkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCopySkin As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''phCopySkinResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phCopySkinResults As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
