'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.Aggregator

    Partial Public Class ManageAggregator

        '''<summary>
        '''lblTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTabs As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmdAddModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddModule As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdAddTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddTab As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdAddAllModules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddAllModules As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dlTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlTabs As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''lblCssTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCssTheme As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboTabSkin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboTabSkin As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblTabTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTabTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboTabTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboTabTemplate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWidth As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeight As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblAutoHide control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAutoHide As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkHideTitles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideTitles As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblShowPrevNext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShowPrevNext As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkShowPrevNext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowPrevNext As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblHideSingleTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHideSingleTab As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkHideSingleTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideSingleTab As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblActiveHover control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActiveHover As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkActiveHover control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkActiveHover As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblActiveHoverDelay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActiveHoverDelay As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtActiveHoverDelay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtActiveHoverDelay As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblHideTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHideTabs As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkHideTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideTabs As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblDefaultTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDefaultTab As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDefaultTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDefaultTab As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblRememberLastOpenTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRememberLastOpenTab As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkRememberLastOpenTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRememberLastOpenTab As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cpvMain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cpvMain As Global.DNNStuff.Aggregator.CustomPropertiesViewer

        '''<summary>
        '''lblCustomPropertyHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomPropertyHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTargets control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTargets As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmdAddTarget control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddTarget As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''grdTargets control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdTargets As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblRSSUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRSSUrl As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRSSUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRSSUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblRSSMaxItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRSSMaxItems As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRSSMaxItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRSSMaxItems As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblRSSCacheTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRSSCacheTime As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRSSCacheTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRSSCacheTime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblRSSTabCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRSSTabCaption As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRSSTabCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRSSTabCaption As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblRSSUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRSSUsername As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRSSUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRSSUsername As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblRSSPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRSSPassword As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRSSPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRSSPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblQuickTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblQuickTabs As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmdQuickTabsAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdQuickTabsAdd As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtQuickTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQuickTabs As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
