'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.Aggregator

    Partial Public Class ManageScript

        '''<summary>
        '''lblLoadScript1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLoadScript1 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkLoadScript1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLoadScript1 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblUseHostedScript1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUseHostedScript1 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkUseHostedScript1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUseHostedScript1 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblHostedScript1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHostedScript1 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtHostedScript1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHostedScript1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblLoadScript2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLoadScript2 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkLoadScript2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLoadScript2 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblUseHostedScript2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUseHostedScript2 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkUseHostedScript2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUseHostedScript2 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblHostedScript2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHostedScript2 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtHostedScript2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHostedScript2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
